[package]
name = "vos-rs"
version = "0.1.0"
authors = ["xeex <47105257+xeex@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
ghakuf = "0.5.6"
